### ISSUE TITLE
if-else文の記載に関して

### ISSUE THREAD

**Issue by TakaoWing** [TomoyaKishimoto/REX_pusleSensor#1]
作成途中ですみません．気になってしまったので，イシューあげさせてもらいました！！
https://github.com/TomoyaKishimoto/REX_pusleSensor/blob/74a849f953549b45446501552c598fecf8c0b489/PulseSensor/1/1.ino#L15-L23
上記プログラムを以下のようにした方がいいのかなと思います．
```c
if(条件) // もし条件を満たしたなら
{
 // 処理
}
else // でなければ
{
 // 処理
}
```
隙間が空いてしまうと，一見ifはこれで終わっていると見えてしまうため，elseが上のif文の「でなければ」というのがわかりやすいためです．

**Comment by TomoyaKishimoto** [comment]
確かにそのほうがわかりやすいですね！
修正しました、ありがとうございます。
